spring:
  h2:
    console:
      enabled: true
    datasource:
      url: ${database.url}
      username: ${database.username}
      password: ${database.password}
      driver-class-name: org.h2.Driver
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect